# Generated by Django 3.1.7 on 2021-03-24 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_customuser_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='subject')),
                ('price', models.PositiveIntegerField(verbose_name='subject')),
            ],
            options={
                'verbose_name': 'price list',
                'verbose_name_plural': 'price lists',
                'db_table': 'price_list',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('surname', models.CharField(max_length=100, verbose_name='surname')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('patronymic', models.CharField(max_length=100, verbose_name='patronymic')),
                ('phone', models.CharField(max_length=16, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_addresses', to='users.useraddress', verbose_name='address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'service',
            },
        ),
    ]


