# Generated by Django 3.1.7 on 2021-03-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
    ]
