# Generated by Django 3.1.7 on 2021-03-07 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_values', '0002_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuewatergaselectricalmeters',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter', to='send_values.watergaselectricalmeters'),
        ),
        migrations.AlterField(
            model_name='valuewatergaselectricalmeters',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
