# Generated by Django 3.1.7 on 2021-03-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210318_1101'),
        ('send_values', '0007_meterstype_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='watergaselectricalmeters',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_address', to='users.useraddress', verbose_name='address'),
        ),
    ]
