# Generated by Django 3.1.7 on 2021-03-25 08:44

from django.db import migrations, models
import src.articles.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_group_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=src.articles.models.article_path, verbose_name='image'),
        ),
    ]
