# Generated by Django 3.1.7 on 2021-03-06 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
            ],
            options={
                'db_table': 'task_type',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, verbose_name='subject')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('completed_at', models.DateTimeField(default=None, null=True, verbose_name='completed_at')),
                ('status', models.CharField(choices=[('new', 'new'), ('recieved', 'recieved'), ('in_work', 'in_work'), ('rejected', 'rejected'), ('complete', 'complete')], default='new', max_length=8, verbose_name='status')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('house', models.CharField(max_length=10, verbose_name='house')),
                ('building', models.CharField(blank=True, max_length=10, null=True, verbose_name='building')),
                ('apartment', models.CharField(max_length=10, verbose_name='apartment')),
                ('surname', models.CharField(max_length=100, verbose_name='surname')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('patronymic', models.CharField(max_length=100, verbose_name='patronymic')),
                ('phone', models.CharField(max_length=11, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('performer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performers', to=settings.AUTH_USER_MODEL, verbose_name='performer')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasktype', verbose_name='task_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
