# Generated by Django 3.1.7 on 2021-03-08 17:47

from django.db import migrations, models
import django.db.models.deletion


def apply_migration(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    UserAddress = apps.get_model('users', 'UserAddress')

    tasks_list = []
    for i in Task.objects.all():
        address = UserAddress.objects.get_or_create(
            city=i.city,
            street=i.street,
            house=i.house,
            building=i.building,
            apartment=i.apartment,
            user=i.user
        )
        i.address = address
        tasks_list.append(i)

    Task.objects.bulk_update(tasks_list, ['address'])


def revert_migration(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')

    tasks_list = []
    for i in Task.objects.all():
        i.city = i.address.city
        i.street = i.address.street
        i.house = i.address.house
        i.building = i.address.building
        i.apartment = i.address.apartment
        tasks_list.append(i)

    Task.objects.bulk_update(
        tasks_list,
        ['city', 'street', 'house', 'building', 'apartment']
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_hardcoded_groups'),
        ('tasks', '0002_group_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'verbose_name': 'Тип заявки', 'verbose_name_plural': 'Типы заявок'},
        ),
        migrations.AddField(
            model_name='task',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.useraddress', verbose_name='address'),
        ),
        migrations.RunPython(apply_migration, revert_migration),
        migrations.RemoveField(
            model_name='task',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='building',
        ),
        migrations.RemoveField(
            model_name='task',
            name='city',
        ),
        migrations.RemoveField(
            model_name='task',
            name='house',
        ),
        migrations.RemoveField(
            model_name='task',
            name='street',
        ),
        migrations.AlterField(
            model_name='task',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.useraddress', verbose_name='address'),
        ),
    ]
