# Generated by Django 3.1.7 on 2021-03-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_add_useraddress_fk_to_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
