# Generated by Django 3.1.7 on 2021-03-15 10:19

from django.db import migrations, models
import src.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_tasktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to=src.tasks.models.user_directory_path, verbose_name='attachment'),
        ),
    ]
