# Generated by Django 3.1.7 on 2021-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210324_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('recieved', 'recieved'), ('in work', 'in work'), ('rejected', 'rejected'), ('complete', 'complete')], default='new', max_length=8, verbose_name='status'),
        ),
    ]
