# Generated by Django 3.1.7 on 2021-03-25 19:44

from django.db import migrations, models
import src.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20210325_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=src.tasks.models.user_directory_path, verbose_name='attachment'),
        ),
    ]
