# Generated by Django 3.1.7 on 2021-03-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_taskstatus_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='task',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='patronymic'),
        ),
    ]
