# Generated by Django 3.1.7 on 2021-03-06 14:04

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name='Жильцы'),
        Group(name='Сотрудники ТСЖ'),
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            Group(name='Жильцы'),
            Group(name='Сотрудники ТСЖ'),
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_role'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
