# Generated by Django 3.1.7 on 2021-03-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210318_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='city',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='apartment'),
        ),
    ]
