# Generated by Django 3.1.7 on 2021-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210318_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='personal account'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='main user address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='patronymic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='surname'),
        ),
    ]
