# Generated by Django 3.1.7 on 2021-03-24 12:15

from django.db import migrations, models
import src.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210320_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to=src.users.models.user_directory_path, verbose_name='attachment'),
        ),
    ]
