# Generated by Django 3.1.7 on 2021-03-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicsettings',
            options={'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
    ]
