# Generated by Django 3.1.7 on 2021-03-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_settings', '0002_auto_20210318_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicsettings',
            options={'verbose_name': 'dynamic setting', 'verbose_name_plural': 'dynamic settings'},
        ),
    ]
